# Generated by Django 6.0.3 on 2026-03-07 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(default=datetime.date.today)),
                ('persons', models.ManyToManyField(to='restaurant.persons')),
            ],
        ),
    ]
