# Generated by Django 6.0.3 on 2026-03-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='phone',
            field=models.IntegerField(max_length=13),
        ),
    ]
