# Generated by Django 6.0.3 on 2026-03-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='persons',
        ),
        migrations.AddField(
            model_name='persons',
            name='persons',
            field=models.IntegerField(default=1),
        ),
    ]
